services:
  ci:
    build:
      context: .
      target: comicbox-ci
    container_name: comicbox-ci
    entrypoint:
      - sleep
      - infinity
    environment:
      - PYTHONUNBUFFERED=1
    image: comicbox-ci:ci
    volumes:
      - ./test-results:/app/test-results
      - ./dist:/app/dist
