services:
  ci:
    build:
      context: .
      target: comicbox-ci
    image: comicbox-ci:ci
    container_name: comicbox-ci
    volumes:
      - ./test-results:/app/test-results
      - ./dist:/app/dist
    environment:
      - PYTHONUNBUFFERED=1
    entrypoint: [sleep, infinity]
