services:
  comicbox-builder:
    build:
      context: .
      args:
        CODEX_BUILDER_BASE_VERSION:
    image: comicbox-builder
    container_name: comicbox-builder
  comicbox-test:
    image: comicbox-builder
    container_name: comicbox-test
    command: ./test.sh
    volumes:
      - ./test-results/:/app/test-results/
  comicbox-lint:
    image: comicbox-builder
    container_name: comicbox-lint
    command: ./lint.sh
  comicbox-build:
    image: comicbox-builder
    container_name: comicbox-build
    volumes:
      - ./dist/:/app/dist/
    command: poetry build
