services:
  comicbox-builder:
    build: .
    image: comicbox-builder
    container_name: comicbox-builder
  comicbox-lint:
    image: comicbox-builder
    container_name: comicbox-lint
    command: make lint
  comicbox-test:
    image: comicbox-builder
    container_name: comicbox-test
    command: make test
    volumes:
      - ./test-results/:/app/test-results/
  comicbox-build:
    image: comicbox-builder
    container_name: comicbox-build
    volumes:
      - ./dist/:/app/dist/
    command: uv build
