"""Nested Publishing Tags."""

from comicbox.schemas.comicbox import (
    IMPRINT_KEY,
    NAME_KEY,
    PUBLISHER_KEY,
    SERIES_KEY,
    VOLUME_COUNT_KEY,
    VOLUME_ISSUE_COUNT_KEY,
    VOLUME_KEY,
    VOLUME_NUMBER_KEY,
)

PUBLISHER_NAME_KEYPATH = f"{PUBLISHER_KEY}.{NAME_KEY}"
IMPRINT_NAME_KEYPATH = f"{IMPRINT_KEY}.{NAME_KEY}"
SERIES_NAME_KEYPATH = f"{SERIES_KEY}.{NAME_KEY}"
VOLUME_COUNT_KEYPATH = f"{SERIES_KEY}.{VOLUME_COUNT_KEY}"
VOLUME_NUMBER_KEYPATH = f"{VOLUME_KEY}.{VOLUME_NUMBER_KEY}"
ISSUE_COUNT_KEYPATH = f"{VOLUME_KEY}.{VOLUME_ISSUE_COUNT_KEY}"
